### PR TITLE
Add management access to Hetzner servers too

### PR DESCRIPTION
**Pull request by noplanman**
This PR allows management servers to also set up the connection to Hetzner servers, not just normal and rsync.net ones.

There is 1 thing that I've added to my SSH authorized_keys file, but it requires the `jmespath` package installed on the host executing the playbook.
It limits the management server to only have access to the actual repositories on the backup servers. As it is now, the SSH public key is allowed full access to ALL backup servers.

Not sure if I'm being paranoid here, but I prefer access on a need-to-have basis.

My change basically adds a `key_options` value when copying the public key to the servers:
```yaml
key_options: "command=\"borg serve --restrict-to-path {{ borgbackup_normal_server_backup_paths[item.fqdn] | join(' --restrict-to-path ') }}\",no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-user-rc"
```

(I have some extra code that creates the `borgbackup_normal_server_backup_paths` fact which is what requires the `jmespath` package)

### CODE REVIEW

**Comment by noplanman** [comment]
@stroobl @dverhelst Any idea why the flake8 linter is suddenly failing the tests?

**Comment by stroobl** [comment]
The contents of the PR looks good to me.

I'm not able to reproduce the flake8 issue on my local setup, but it's probably related to the symlinks used in the test directory. @dverhelst any idea?

**Comment by stroobl** [comment]
@noplanman I think I found a fix for the flake8 build failure while I was working on the Icinga2 collection: add the .flake8 config in the root of the role. Looks like Travis runs the tests differently now.

**Comment by noplanman** [comment]
@stroobl Perfect, tests work now 👍

**Pull request merged**
