### PR TITLE
Extend borg backup script

### PR DESCRIPTION
**Pull request by noplanman**
- ~Remove an unused parameter requirement from the "mount" command.~
- Add a new "check" command for easy backup consistency checking.

### CODE REVIEW

**Comment by noplanman** [comment]
@stroobl Ok, I see what you mean. I've removed the "fix" to the `mount` command.
Will you add the parameter correctly then?

**Comment by stroobl** [comment]
@noplanman You can also fix it you have the time and want to fix it, but I just think it's confusing to remove the parameter now without having an actual fix for the broken half functionality.
If you prefer not to look into it now, I'll log a bug and fix it later.

**Comment by noplanman** [comment]
@stroobl If you can create an issue where we can discuss, I'm happy to write a fix :+1:

**Comment by stroobl** [comment]
@noplanman Ok, I'll create an issue for the problem and merge this PR already. Thanks!

**Pull request merged**
